spring:
  application:
    name: productsapp
  datasource:
    url: jdbc:mysql://localhost:3306/productsappv2
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: true
    default-model-expand-depth: -1